name: reviewdog
on: [pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    env:
      CI: true
      NODE_ENV: development
    steps:
      - name: Cancel running workflows in same branch
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "~16.10"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: "**/node_modules"
          restore-keys: |
            ${{ runner.os }}-npm-
      - run: npm install
      - uses: reviewdog/action-eslint@v1
        with:
          level: info
          eslint_flags: "src --ext .js,.ts,.tsx"
